language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

script:
  - mvn test

deploy:
  - provider: script
    script: cp .travis.settings.xml $HOME/.m2/settings.xml \
      && sed -i.bak  "s/<password>.*<\/password>/<password>${GH_TOKEN}<\/password>/g" .travis.settings.xml \
      && cat .travis.settings.xml && mvn deploy
    skip_cleanup: true
    on:
      branch: master